---
- name: check grub file
  shell: test -f  /boot/grub/menu.lst
  register: grub_file
  failed_when: False


- name: update grub
  command: "sudo update-grub -y"
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: grub_file.rc != 0

- name: update apt-packages
  apt: "upgrade=dist update_cache=yes"
